// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqmxnpqkimbvphshtmge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxbXhucHFraW1idnBoc2h0bWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTgxMDQsImV4cCI6MjA1OTQ5NDEwNH0.rvxOsnJ6u1f9sy36Er5iGlchbX71IpkOtruzEWLbChY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);