
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmruyytifinnlzidalbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtcnV5eXRpZmlubmx6aWRhbGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTA0NzcsImV4cCI6MjA1OTM2NjQ3N30.Ml1vk39NmjPfnxc5e-sWaNMkwg2JIR8BFDm3ivG4Ry0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
